# Generated by Django 5.0.6 on 2025-04-01 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry_app', '0002_businessad'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessad',
            name='delivery_areas',
            field=models.CharField(blank=True, help_text='Areas where delivery is available', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='businessad',
            name='free_delivery',
            field=models.BooleanField(default=False, help_text='Whether free delivery is available'),
        ),
        migrations.AddField(
            model_name='businessad',
            name='home_delivery',
            field=models.BooleanField(default=False, help_text='Whether home delivery is available'),
        ),
        migrations.AddField(
            model_name='businessad',
            name='offers',
            field=models.TextField(blank=True, help_text='Special offers and promotions', null=True),
        ),
    ]
